name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'
  push:
    branches:
      - master
      - 'feature/*'
    paths:
      - 'tickets/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
